backend:
    # Choose the backend you prefer (GitHub, GitLab, BitBucket)
    # Reference: https://www.netlifycms.org/docs/authentication-backends/
    name: github
    branch: master
    repo: zachcb/zachcb.com
media_folder: "static/images"
public_folder: "static/images"
  
collections:
  - name: "posts"
    label: "Post"
    folder: "data/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Description", name: "description", widget: "string" }
      - label: "Hero"
        name: "hero"
        widget: "image"
        default: "/static/images/oib44ois27m01.jpg"
        media_library:
          config:
            multiple: true
        