[build]
  command = "yarn build"
  functions = "functions"
  publish = "dist"

[dev]
  command = "yarn develop"
  port = 8080
  targetPort = 8080
  publish = "dist"

# Redirects
[[redirects]]
  from = "/add"
  to = "/add-example"
  status = 301
  force = true